# Setting the format of the prompt
format = """
$username\
$directory\
$all\
$character"""

right_format = """$time"""

# Inserts a blank line between shell prompts
add_newline = true

# Making a single line prompt
[line_break]
disabled = false


# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red) "


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Adding Battery status to the prompt
[battery]
#full_symbol = "🔋 "
full_symbol = " "
#charging_symbol = "⚡️ "
charging_symbol = " "
#discharging_symbol = "💀 "
discharging_symbol = " "

[[battery.display]] # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]] # "bold yellow" style and 💦 symbol when capacity is between 10% and 30%
threshold = 30
style = "yellow"
#discharging_symbol = " "
discharging_symbol = " "

# when capacity is over 30%, the battery indicator to be displayed
#[[battery.display]] # "bold yellow" style and 💦 symbol when capacity is between 10% and 30%
#threshold = 100
#style = "green"
#discharging_symbol = " " 

# Setting Icons for git status
[git_status]
style = "bold white"
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
up_to_date = "✓"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

#ahead = "⇡${count}"
#diverged = "⇕⇡${ahead_count}⇣${behind_count}"
#behind = "⇣${count}"


# Setting sudo icon

#[sudo]
#style = "bold green"
#symbol = "👩‍💻 "
#symbol = "🧙"
#disabled = false


# Setting time on the prompt

[time]
disabled = false
format = ' [\[ $time \]]($style) '
time_format = "%T"
#utc_time_offset = "-5"
time_range = "00:00:00-24:00:00"
use_12hr = false
style = "bold green"
#time = 10:03:16

[username]
#style_user = "white bold"
style_user = "yellow bold"
style_root = "black bold"
#format = "user: [$user]($style) "
#format = "[$user : ]($style)"
format = "[🚀 : ]($style)"
disabled = false
show_always = true

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
#style = "bold orange"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

#[package]
#symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
#symbol = " "
#symbol = "🐍 "
#symbol = "👾 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

